In [1]:
import sys
print(sys.version)

3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [2]:
import sys
print(sys.executable)
print(sys.path)

c:\Users\USER\ml_tf\Scripts\python.exe
['C:\\Program Files\\Python313\\python313.zip', 'C:\\Program Files\\Python313\\DLLs', 'C:\\Program Files\\Python313\\Lib', 'C:\\Program Files\\Python313', 'c:\\Users\\USER\\ml_tf', '', 'c:\\Users\\USER\\ml_tf\\Lib\\site-packages']

In [3]:
import sys
print(sys.executable)
print(sys.version)

c:\Users\USER\ml_tf\Scripts\python.exe
3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [4]:
!where python
!jupyter kernelspec list

c:\Users\USER\ml_tf\Scripts\python.exe
C:\Program Files\Python313\python.exe
C:\Users\USER\AppData\Local\Programs\Python\Python314\python.exe
C:\Users\USER\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\USER\AppData\Local\Python\bin\python.exe
Available kernels:
  python3    C:\Users\USER\ml_tf\share\jupyter\kernels\python3
  ml_env     C:\Users\USER\AppData\Roaming\jupyter\kernels\ml_env
  ml_env2    C:\Users\USER\AppData\Roaming\jupyter\kernels\ml_env2
  ml_tf      C:\Users\USER\AppData\Roaming\jupyter\kernels\ml_tf
  py313      C:\Users\USER\AppData\Roaming\jupyter\kernels\py313

In [5]:
import ipykernel
print(ipykernel.__file__)

c:\Users\USER\ml_tf\Lib\site-packages\ipykernel\__init__.py

In [6]:
import os
print(os.environ.get("VIRTUAL_ENV"))

C:\Users\USER\ml_tf

In [7]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [8]:
import sys
print(sys.executable)
print(sys.prefix)

c:\Users\USER\ml_tf\Scripts\python.exe
c:\Users\USER\ml_tf

In [9]:
import numpy as np 
import tensorflow as tensorflow
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [10]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 2, 10, 3,
                       10, 12, 5, 9, 11, 2, 6, 1],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [11]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30               2            0
6            0.35             19              10            0
7            0.18             22               3            1
8            0.45             35              10            0
9            0.05             24              12            1
10           0.80             33               5            0
11           0.27             33               9            1
12           0.55             21              11            0
13           0.70             25               2            0
14           0.12             20               6            1
15           0.30             29               1            1

 # let's divide in x and y

In [12]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [13]:
X = df[["soil_moisture", "temperature_c", "sunlight_hours"]]
Y = df[['needs_water']]

## Normalisation
### Mean and Max scaler

In [14]:
X_min=X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min + 1e-8)

In [15]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.090909
6        0.400000         0.0000        0.818182
7        0.173333         0.1875        0.181818
8        0.533333         1.0000        0.818182
9        0.000000         0.3125        1.000000
10       1.000000         0.8750        0.363636
11       0.293333         0.8750        0.727273
12       0.666667         0.1250        0.909091
13       0.866667         0.3750        0.090909
14       0.093333         0.0625        0.454545
15       0.333333         0.6250        0.000000

In [16]:
# train and test split
X_train, X_test, y_train, y_test = train_test_split(
  X_scaled, Y, test_size=0.25, random_state=42,stratify=Y)

In [17]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(
    optimizer='opt',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
history_full = model.fit(X_train,y_train, epochs=100, batch_size=len(X_train),verbose=1)
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=1,
        verbose=1
)
history_minibatch=model.fit(X_train,y_train,epochs=100,batch_size=100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 9s 9s/step - accuracy: 0.2500 - loss: 0.7818
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 361ms/step - accuracy: 0.2500 - loss: 0.7810
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 557ms/step - accuracy: 0.2500 - loss: 0.7802
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 0.7794
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 0.7786
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 554ms/step - accuracy: 0.2500 - loss: 0.7778
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 732ms/step - accuracy: 0.2500 - loss: 0.7770
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - accuracy: 0.2500 - loss: 0.7762
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - accuracy: 0.2500 - loss: 0.7754
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 480ms/step - accuracy: 0.2500 - loss: 0.7744
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 719ms/step - accuracy: 0.2500 - loss: 0.7735
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step - accuracy: 0.2500 - loss: 0.7726
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step - accuracy: 0.2500 - loss: 0.7716
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 569ms/step - accuracy: 0.2500 - loss: 0.7707
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 0.2500 - loss: 0.7697
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 689ms/step - accuracy: 0.2500 - loss: 0.7688
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 651ms/step - accuracy: 0.2500 - loss: 0.7679
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - accuracy: 0.2500 - loss: 0.7670
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - accuracy: 0.2500 - loss: 0.7660
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 841ms/step - accuracy: 0.2500 - loss: 0.7651
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 479ms/step - accuracy: 0.2500 - loss: 0.7643
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step - accuracy: 0.2500 - loss: 0.7635
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - accuracy: 0.2500 - loss: 0.7626
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 819ms/step - accuracy: 0.2500 - loss: 0.7618
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 373ms/step - accuracy: 0.2500 - loss: 0.7610
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - accuracy: 0.2500 - loss: 0.7602
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 258ms/step - accuracy: 0.2500 - loss: 0.7594
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 569ms/step - accuracy: 0.2500 - loss: 0.7586
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 0.7578
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2500 - loss: 0.7571
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - accuracy: 0.2500 - loss: 0.7563
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 258ms/step - accuracy: 0.2500 - loss: 0.7555
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 596ms/step - accuracy: 0.2500 - loss: 0.7547
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 549ms/step - accuracy: 0.2500 - loss: 0.7540
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 515ms/step - accuracy: 0.3333 - loss: 0.7532
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 595ms/step - accuracy: 0.3333 - loss: 0.7524
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - accuracy: 0.3333 - loss: 0.7516
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - accuracy: 0.3333 - loss: 0.7509
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 0.3333 - loss: 0.7501
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step - accuracy: 0.3333 - loss: 0.7494
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step - accuracy: 0.3333 - loss: 0.7486
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 737ms/step - accuracy: 0.3333 - loss: 0.7478
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 724ms/step - accuracy: 0.3333 - loss: 0.7470
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 274ms/step - accuracy: 0.3333 - loss: 0.7462
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 834ms/step - accuracy: 0.3333 - loss: 0.7454
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 526ms/step - accuracy: 0.3333 - loss: 0.7446
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 716ms/step - accuracy: 0.3333 - loss: 0.7439
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 588ms/step - accuracy: 0.3333 - loss: 0.7431
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 355ms/step - accuracy: 0.3333 - loss: 0.7423
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 704ms/step - accuracy: 0.3333 - loss: 0.7416
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 582ms/step - accuracy: 0.3333 - loss: 0.7408
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 446ms/step - accuracy: 0.3333 - loss: 0.7400
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 667ms/step - accuracy: 0.3333 - loss: 0.7393
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 599ms/step - accuracy: 0.3333 - loss: 0.7385
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 541ms/step - accuracy: 0.3333 - loss: 0.7377
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 863ms/step - accuracy: 0.3333 - loss: 0.7370
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - accuracy: 0.3333 - loss: 0.7364
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 665ms/step - accuracy: 0.3333 - loss: 0.7358
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 570ms/step - accuracy: 0.3333 - loss: 0.7352
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.3333 - loss: 0.7346
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - accuracy: 0.3333 - loss: 0.7340
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 594ms/step - accuracy: 0.3333 - loss: 0.7334
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3333 - loss: 0.7328
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 687ms/step - accuracy: 0.3333 - loss: 0.7322
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 744ms/step - accuracy: 0.3333 - loss: 0.7316
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step - accuracy: 0.3333 - loss: 0.7310
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - accuracy: 0.3333 - loss: 0.7304
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 765ms/step - accuracy: 0.3333 - loss: 0.7298
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step - accuracy: 0.3333 - loss: 0.7292
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step - accuracy: 0.3333 - loss: 0.7286
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - accuracy: 0.3333 - loss: 0.7279
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 745ms/step - accuracy: 0.3333 - loss: 0.7273
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - accuracy: 0.3333 - loss: 0.7267
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 732ms/step - accuracy: 0.3333 - loss: 0.7261
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 463ms/step - accuracy: 0.3333 - loss: 0.7255
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 419ms/step - accuracy: 0.3333 - loss: 0.7249
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step - accuracy: 0.3333 - loss: 0.7242
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 381ms/step - accuracy: 0.3333 - loss: 0.7236
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 723ms/step - accuracy: 0.3333 - loss: 0.7230
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step - accuracy: 0.3333 - loss: 0.7224
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 517ms/step - accuracy: 0.3333 - loss: 0.7219
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - accuracy: 0.3333 - loss: 0.7214
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 936ms/step - accuracy: 0.3333 - loss: 0.7209
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 579ms/step - accuracy: 0.3333 - loss: 0.7203
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 460ms/step - accuracy: 0.3333 - loss: 0.7197
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - accuracy: 0.3333 - loss: 0.7190
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - accuracy: 0.3333 - loss: 0.7183
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step - accuracy: 0.3333 - loss: 0.7176
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 835ms/step - accuracy: 0.3333 - loss: 0.7170
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3333 - loss: 0.7164
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 657ms/step - accuracy: 0.3333 - loss: 0.7159
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 871ms/step - accuracy: 0.3333 - loss: 0.7154
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3333 - loss: 0.7148
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 784ms/step - accuracy: 0.3333 - loss: 0.7143
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3333 - loss: 0.7137
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 745ms/step - accuracy: 0.3333 - loss: 0.7132
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 689ms/step - accuracy: 0.3333 - loss: 0.7127
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - accuracy: 0.3333 - loss: 0.7121
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - accuracy: 0.3333 - loss: 0.7116
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step - accuracy: 0.3333 - loss: 0.7111
Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 93ms/step - accuracy: 0.3333 - loss: 0.7118 - val_accuracy: 0.5000 - val_loss: 0.6086
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.4167 - loss: 0.7050 - val_accuracy: 0.5000 - val_loss: 0.6063
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 175ms/step - accuracy: 0.5000 - loss: 0.6981 - val_accuracy: 0.5000 - val_loss: 0.6038
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 327ms/step - accuracy: 0.5833 - loss: 0.6911 - val_accuracy: 0.5000 - val_loss: 0.6012
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.5833 - loss: 0.6833 - val_accuracy: 0.5000 - val_loss: 0.5979
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.5833 - loss: 0.6758 - val_accuracy: 0.5000 - val_loss: 0.5950
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.6667 - loss: 0.6685 - val_accuracy: 0.7500 - val_loss: 0.5918
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.7500 - loss: 0.6632 - val_accuracy: 0.7500 - val_loss: 0.5889
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 230ms/step - accuracy: 0.7500 - loss: 0.6586 - val_accuracy: 0.7500 - val_loss: 0.5861
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.7500 - loss: 0.6544 - val_accuracy: 0.7500 - val_loss: 0.5832
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - accuracy: 0.7500 - loss: 0.6503 - val_accuracy: 0.7500 - val_loss: 0.5812
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.7500 - loss: 0.6462 - val_accuracy: 0.7500 - val_loss: 0.5806
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.6667 - loss: 0.6427 - val_accuracy: 0.7500 - val_loss: 0.5800
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.6667 - loss: 0.6393 - val_accuracy: 0.7500 - val_loss: 0.5793
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.7500 - loss: 0.6364 - val_accuracy: 0.7500 - val_loss: 0.5783
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.6667 - loss: 0.6336 - val_accuracy: 0.7500 - val_loss: 0.5773
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - accuracy: 0.6667 - loss: 0.6307 - val_accuracy: 0.7500 - val_loss: 0.5758
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.7500 - loss: 0.6279 - val_accuracy: 0.7500 - val_loss: 0.5740
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 126ms/step - accuracy: 0.6667 - loss: 0.6251 - val_accuracy: 0.7500 - val_loss: 0.5723
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - accuracy: 0.6667 - loss: 0.6224 - val_accuracy: 0.7500 - val_loss: 0.5705
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.7500 - loss: 0.6194 - val_accuracy: 0.7500 - val_loss: 0.5686
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 184ms/step - accuracy: 0.6667 - loss: 0.6168 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.7500 - loss: 0.6127 - val_accuracy: 0.7500 - val_loss: 0.5642
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 167ms/step - accuracy: 0.6667 - loss: 0.6115 - val_accuracy: 0.7500 - val_loss: 0.5624
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 139ms/step - accuracy: 0.7500 - loss: 0.6088 - val_accuracy: 0.7500 - val_loss: 0.5606
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 147ms/step - accuracy: 0.6667 - loss: 0.6061 - val_accuracy: 0.7500 - val_loss: 0.5588
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 209ms/step - accuracy: 0.7500 - loss: 0.6037 - val_accuracy: 0.7500 - val_loss: 0.5569
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 155ms/step - accuracy: 0.7500 - loss: 0.6013 - val_accuracy: 0.7500 - val_loss: 0.5551
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 172ms/step - accuracy: 0.7500 - loss: 0.5988 - val_accuracy: 0.7500 - val_loss: 0.5532
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 4s 287ms/step - accuracy: 0.7500 - loss: 0.5964 - val_accuracy: 0.7500 - val_loss: 0.5514
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 69ms/step - accuracy: 0.7500 - loss: 0.5936 - val_accuracy: 0.7500 - val_loss: 0.5488
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.7500 - loss: 0.5910 - val_accuracy: 0.7500 - val_loss: 0.5467
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.7500 - loss: 0.5896 - val_accuracy: 0.7500 - val_loss: 0.5446
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - accuracy: 0.7500 - loss: 0.5872 - val_accuracy: 0.7500 - val_loss: 0.5427
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 176ms/step - accuracy: 0.7500 - loss: 0.5843 - val_accuracy: 0.7500 - val_loss: 0.5409
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.8333 - loss: 0.5827 - val_accuracy: 0.7500 - val_loss: 0.5389
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7500 - loss: 0.5803 - val_accuracy: 0.7500 - val_loss: 0.5368
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.5774 - val_accuracy: 0.7500 - val_loss: 0.5354
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.5758 - val_accuracy: 0.7500 - val_loss: 0.5333
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.5735 - val_accuracy: 0.7500 - val_loss: 0.5311
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8333 - loss: 0.5708 - val_accuracy: 0.7500 - val_loss: 0.5295
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.7500 - loss: 0.5690 - val_accuracy: 0.7500 - val_loss: 0.5273
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7500 - loss: 0.5664 - val_accuracy: 0.7500 - val_loss: 0.5257
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7500 - loss: 0.5645 - val_accuracy: 0.7500 - val_loss: 0.5234
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 95ms/step - accuracy: 0.8333 - loss: 0.5620 - val_accuracy: 0.7500 - val_loss: 0.5217
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - accuracy: 0.8333 - loss: 0.5601 - val_accuracy: 0.7500 - val_loss: 0.5195
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.7500 - loss: 0.5577 - val_accuracy: 0.7500 - val_loss: 0.5178
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.7500 - loss: 0.5557 - val_accuracy: 1.0000 - val_loss: 0.5154
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8333 - loss: 0.5534 - val_accuracy: 1.0000 - val_loss: 0.5137
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8333 - loss: 0.5512 - val_accuracy: 1.0000 - val_loss: 0.5120
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.8333 - loss: 0.5493 - val_accuracy: 1.0000 - val_loss: 0.5097
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.8333 - loss: 0.5470 - val_accuracy: 1.0000 - val_loss: 0.5078
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.8333 - loss: 0.5450 - val_accuracy: 1.0000 - val_loss: 0.5054
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.8333 - loss: 0.5429 - val_accuracy: 1.0000 - val_loss: 0.5036
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 136ms/step - accuracy: 0.7500 - loss: 0.5406 - val_accuracy: 1.0000 - val_loss: 0.5011
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 128ms/step - accuracy: 0.7500 - loss: 0.5387 - val_accuracy: 1.0000 - val_loss: 0.4992
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - accuracy: 0.8333 - loss: 0.5364 - val_accuracy: 1.0000 - val_loss: 0.4968
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.8333 - loss: 0.5349 - val_accuracy: 1.0000 - val_loss: 0.4949
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.8333 - loss: 0.5328 - val_accuracy: 1.0000 - val_loss: 0.4930
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.8333 - loss: 0.5308 - val_accuracy: 1.0000 - val_loss: 0.4912
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 133ms/step - accuracy: 0.9167 - loss: 0.5287 - val_accuracy: 1.0000 - val_loss: 0.4895
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.9167 - loss: 0.5267 - val_accuracy: 1.0000 - val_loss: 0.4871
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - accuracy: 0.9167 - loss: 0.5250 - val_accuracy: 1.0000 - val_loss: 0.4852
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - accuracy: 0.9167 - loss: 0.5228 - val_accuracy: 1.0000 - val_loss: 0.4827
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.8333 - loss: 0.5204 - val_accuracy: 1.0000 - val_loss: 0.4801
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9167 - loss: 0.5192 - val_accuracy: 1.0000 - val_loss: 0.4783
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 91ms/step - accuracy: 0.9167 - loss: 0.5171 - val_accuracy: 1.0000 - val_loss: 0.4763
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.8333 - loss: 0.5151 - val_accuracy: 1.0000 - val_loss: 0.4744
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.9167 - loss: 0.5130 - val_accuracy: 1.0000 - val_loss: 0.4724
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.9167 - loss: 0.5110 - val_accuracy: 1.0000 - val_loss: 0.4704
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9167 - loss: 0.5090 - val_accuracy: 1.0000 - val_loss: 0.4685
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.5071 - val_accuracy: 1.0000 - val_loss: 0.4666
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.5052 - val_accuracy: 1.0000 - val_loss: 0.4646
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9167 - loss: 0.5034 - val_accuracy: 1.0000 - val_loss: 0.4626
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.5016 - val_accuracy: 1.0000 - val_loss: 0.4606
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.9167 - loss: 0.4996 - val_accuracy: 1.0000 - val_loss: 0.4579
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.9167 - loss: 0.4972 - val_accuracy: 1.0000 - val_loss: 0.4551
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.4963 - val_accuracy: 1.0000 - val_loss: 0.4532
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9167 - loss: 0.4944 - val_accuracy: 1.0000 - val_loss: 0.4511
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9167 - loss: 0.4927 - val_accuracy: 1.0000 - val_loss: 0.4492
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.4909 - val_accuracy: 1.0000 - val_loss: 0.4471
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9167 - loss: 0.4891 - val_accuracy: 1.0000 - val_loss: 0.4450
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4874 - val_accuracy: 1.0000 - val_loss: 0.4429
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9167 - loss: 0.4857 - val_accuracy: 1.0000 - val_loss: 0.4409
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.9167 - loss: 0.4838 - val_accuracy: 1.0000 - val_loss: 0.4389
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9167 - loss: 0.4821 - val_accuracy: 1.0000 - val_loss: 0.4369
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9167 - loss: 0.4804 - val_accuracy: 1.0000 - val_loss: 0.4348
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.9167 - loss: 0.4785 - val_accuracy: 1.0000 - val_loss: 0.4329
Epoch 89/100

In [20]:
from tensorflow.keras import optimizers

In [21]:
opt = optimizers.SGD(learning_rate=0.01,momentum=0.9)